apiVersion: apps/v1
kind: Deployment
metadata:
  name: crane-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crane-operator
  template:
    metadata:
      labels:
        app: crane-operator
    spec:
      containers:
      - name: controller
        image: jimjuniorb/crane-operator:latest
